import jsPDF from 'jspdf'
import { autoTable } from 'jspdf-autotable'

const BRAND    = [234, 88, 12]    // #ea580c
const DARK     = [17, 24, 39]     // gray-900
const MID_GRAY = [107, 114, 128]  // gray-500
const LIGHT    = [249, 250, 251]  // gray-50

const SIG_H         = 38   // height reserved for signature block (mm)
const SIG_MARGIN    = 14   // side margin
const FOOTER_Y_PAD  = 6    // gap between page content and CatchQuote footer line

function fmt(n) {
  return `$${Number(n).toLocaleString('en-AU', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

function drawSignatureBlock(doc, pageW, pageH, clientName, settings, isLastPage) {
  const sigTop = pageH - SIG_H - 10   // 10mm above absolute bottom
  const midX   = pageW / 2

  // Extra breathing room on last page for physical signing
  const blockTop = isLastPage ? sigTop - 8 : sigTop

  // Divider line
  doc.setDrawColor(220, 220, 220)
  doc.setLineWidth(0.4)
  doc.line(SIG_MARGIN, blockTop, pageW - SIG_MARGIN, blockTop)

  // LEFT — Prepared by
  let y = blockTop + 6
  doc.setFontSize(7)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...MID_GRAY)
  doc.text('PREPARED BY', SIG_MARGIN, y)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text(settings?.designer_name || '', SIG_MARGIN, y + 5)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MID_GRAY)
  doc.text(settings?.designer_position || '', SIG_MARGIN, y + 10)

  // Signature line + label
  const lineY = y + (isLastPage ? 20 : 16)
  doc.setDrawColor(...MID_GRAY)
  doc.setLineWidth(0.3)
  doc.line(SIG_MARGIN, lineY, midX - 8, lineY)
  doc.setFontSize(7)
  doc.text('Signature', SIG_MARGIN, lineY + 3.5)

  const dateY = lineY + 7
  doc.line(SIG_MARGIN, dateY, midX - 8, dateY)
  doc.text('Date', SIG_MARGIN, dateY + 3.5)

  // RIGHT — Confirmed & Accepted by
  const rx = midX + 4
  doc.setFontSize(7)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...MID_GRAY)
  doc.text('CONFIRMED & ACCEPTED BY', rx, y)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text(clientName || '', rx, y + 5)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MID_GRAY)
  doc.text('Client', rx, y + 10)

  doc.setDrawColor(...MID_GRAY)
  doc.setLineWidth(0.3)
  doc.line(rx, lineY, pageW - SIG_MARGIN, lineY)
  doc.setFontSize(7)
  doc.text('Signature', rx, lineY + 3.5)

  doc.line(rx, dateY, pageW - SIG_MARGIN, dateY)
  doc.text('Date', rx, dateY + 3.5)
}

function drawPageFooter(doc, pageNum, totalPages, pageW, pageH) {
  doc.setFontSize(7.5)
  doc.setTextColor(...MID_GRAY)
  doc.setFont('helvetica', 'normal')
  doc.text(
    `Generated by CatchQuote · catchquote.io    Page ${pageNum} of ${totalPages}`,
    pageW / 2,
    pageH - 5,
    { align: 'center' }
  )
}

export function exportQuotePDF({ quote, items, subtotal, gst, total, settings }) {
  const doc   = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()

  // ── Page 1 header ────────────────────────────────────────────────────────────
  doc.setFillColor(...BRAND)
  doc.rect(0, 0, pageW, 42, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(255, 255, 255)
  doc.text('CatchQuote', 14, 18)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(186, 230, 253)
  doc.text('Renovation Quotation Software', 14, 26)

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(28)
  doc.setTextColor(255, 255, 255)
  doc.text('QUOTATION', pageW - 14, 24, { align: 'right' })

  // ── Meta band ────────────────────────────────────────────────────────────────
  doc.setFillColor(...LIGHT)
  doc.rect(0, 42, pageW, 38, 'F')

  const metaY = 52
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('CLIENT', 14, metaY)
  doc.setFont('helvetica', 'normal')
  doc.text(quote.clientName    || '—', 14, metaY + 5)
  doc.text(quote.clientEmail   || '',  14, metaY + 10)
  doc.text(quote.clientAddress || '',  14, metaY + 15)

  const col2 = pageW - 14
  doc.setFont('helvetica', 'bold')
  doc.text('Quote No.',  col2 - 40, metaY)
  doc.text('Date',       col2 - 40, metaY + 7)
  doc.text('Valid Until',col2 - 40, metaY + 14)
  doc.setFont('helvetica', 'normal')
  doc.text(quote.quoteNumber || '—', col2, metaY,      { align: 'right' })
  doc.text(quote.date        || new Date().toLocaleDateString('en-AU'), col2, metaY + 7,  { align: 'right' })
  doc.text(quote.validUntil  || '—', col2, metaY + 14, { align: 'right' })

  if (quote.projectTitle) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(...BRAND)
    doc.text(`Project: ${quote.projectTitle}`, 14, 86)
  }

  // ── Line items table ──────────────────────────────────────────────────────────
  // bottomMargin reserves space for signature block + footer on every page
  const bottomMargin = SIG_H + 18

  autoTable(doc, {
    startY: quote.projectTitle ? 92 : 86,
    head:   [['#', 'Category', 'Description', 'Unit', 'Qty', 'Unit Price', 'Amount']],
    body: items.map((item, i) => [
      i + 1,
      item.category,
      item.description,
      item.unit,
      item.qty,
      fmt(item.unitPrice),
      fmt((parseFloat(item.qty) || 0) * (parseFloat(item.unitPrice) || 0)),
    ]),
    styles:             { fontSize: 9, cellPadding: 3, textColor: DARK },
    headStyles:         { fillColor: BRAND, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [255, 247, 237] },
    columnStyles: {
      0: { cellWidth: 8,  halign: 'center' },
      3: { cellWidth: 16, halign: 'center' },
      4: { cellWidth: 12, halign: 'right' },
      5: { cellWidth: 22, halign: 'right' },
      6: { cellWidth: 26, halign: 'right' },
    },
    margin: { left: 14, right: 14, bottom: bottomMargin },
  })

  const afterTable = doc.lastAutoTable.finalY + 6

  // ── Totals block ─────────────────────────────────────────────────────────────
  const totalsX = pageW - 70
  const totalsW = 56
  const rowH    = 8

  doc.setFillColor(240, 249, 255)
  doc.roundedRect(totalsX - 6, afterTable, totalsW + 6, rowH * 3 + 4, 2, 2, 'F')

  doc.setFontSize(9.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MID_GRAY)
  doc.text('Subtotal (excl. GST)', totalsX, afterTable + rowH * 0.8)
  doc.text(`GST (${(0.1 * 100).toFixed(0)}%)`, totalsX, afterTable + rowH * 1.8)

  doc.setTextColor(...DARK)
  doc.text(fmt(subtotal), pageW - 14, afterTable + rowH * 0.8, { align: 'right' })
  doc.text(fmt(gst),      pageW - 14, afterTable + rowH * 1.8, { align: 'right' })

  const totalRowY = afterTable + rowH * 2.2
  doc.setFillColor(...BRAND)
  doc.roundedRect(totalsX - 6, totalRowY, totalsW + 6, rowH + 2, 2, 2, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10.5)
  doc.setTextColor(255, 255, 255)
  doc.text('TOTAL (incl. GST)', totalsX, totalRowY + rowH * 0.72)
  doc.text(fmt(total), pageW - 14, totalRowY + rowH * 0.72, { align: 'right' })

  // ── Notes ────────────────────────────────────────────────────────────────────
  if (quote.notes) {
    const notesY = totalRowY + rowH + 14
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...DARK)
    doc.text('Notes', 14, notesY)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MID_GRAY)
    const lines = doc.splitTextToSize(quote.notes, pageW - 28)
    doc.text(lines, 14, notesY + 5)
  }

  // ── Per-page: signature block + footer ───────────────────────────────────────
  const totalPages = doc.internal.getNumberOfPages()
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p)
    drawSignatureBlock(doc, pageW, pageH, quote.clientName, settings, p === totalPages)
    drawPageFooter(doc, p, totalPages, pageW, pageH)
  }

  const filename = `quote-${(quote.quoteNumber || 'draft').replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`
  doc.save(filename)
}
