import jsPDF from 'jspdf'
import { autoTable } from 'jspdf-autotable'

const BRAND_BLUE = [234, 88, 12]   // #ea580c orange-600
const DARK      = [17, 24, 39]     // gray-900
const MID_GRAY  = [107, 114, 128]  // gray-500
const LIGHT     = [249, 250, 251]  // gray-50

function fmt(n) {
  return `$${Number(n).toLocaleString('en-AU', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

export function exportQuotePDF({ quote, items, subtotal, gst, total }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()

  // Header band
  doc.setFillColor(...BRAND_BLUE)
  doc.rect(0, 0, pageW, 42, 'F')

  // Logo text
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(255, 255, 255)
  doc.text('CatchQuote', 14, 18)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(186, 230, 253) // brand-200
  doc.text('Renovation Quotation Software', 14, 26)

  // QUOTATION label
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(28)
  doc.setTextColor(255, 255, 255)
  doc.text('QUOTATION', pageW - 14, 24, { align: 'right' })

  // Quote meta block
  doc.setFillColor(...LIGHT)
  doc.rect(0, 42, pageW, 38, 'F')

  const metaY = 52
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)

  // Left — client info
  doc.text('CLIENT', 14, metaY)
  doc.setFont('helvetica', 'normal')
  doc.text(quote.clientName || '—', 14, metaY + 5)
  doc.text(quote.clientEmail || '', 14, metaY + 10)
  doc.text(quote.clientAddress || '', 14, metaY + 15)

  // Right — quote details
  const col2 = pageW - 14
  doc.setFont('helvetica', 'bold')
  doc.text('Quote No.', col2 - 40, metaY)
  doc.text('Date', col2 - 40, metaY + 7)
  doc.text('Valid Until', col2 - 40, metaY + 14)
  doc.setFont('helvetica', 'normal')
  doc.text(quote.quoteNumber || '—', col2, metaY, { align: 'right' })
  doc.text(quote.date || new Date().toLocaleDateString('en-AU'), col2, metaY + 7, { align: 'right' })
  doc.text(quote.validUntil || '—', col2, metaY + 14, { align: 'right' })

  // Project label
  if (quote.projectTitle) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(...BRAND_BLUE)
    doc.text(`Project: ${quote.projectTitle}`, 14, 86)
  }

  // Line items table
  autoTable(doc, {
    startY: quote.projectTitle ? 92 : 86,
    head: [['#', 'Category', 'Description', 'Unit', 'Qty', 'Unit Price', 'Amount']],
    body: items.map((item, i) => [
      i + 1,
      item.category,
      item.description,
      item.unit,
      item.qty,
      fmt(item.unitPrice),
      fmt((parseFloat(item.qty) || 0) * (parseFloat(item.unitPrice) || 0)),
    ]),
    styles: { fontSize: 9, cellPadding: 3, textColor: DARK },
    headStyles: { fillColor: BRAND_BLUE, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [255, 247, 237] },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      3: { cellWidth: 16, halign: 'center' },
      4: { cellWidth: 12, halign: 'right' },
      5: { cellWidth: 22, halign: 'right' },
      6: { cellWidth: 26, halign: 'right' },
    },
    margin: { left: 14, right: 14 },
  })

  const afterTable = doc.lastAutoTable.finalY + 6

  // Totals block
  const totalsX = pageW - 70
  const totalsW = 56
  const rowH = 8

  doc.setFillColor(240, 249, 255)
  doc.roundedRect(totalsX - 6, afterTable, totalsW + 6, rowH * 3 + 4, 2, 2, 'F')

  doc.setFontSize(9.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MID_GRAY)
  doc.text('Subtotal (excl. GST)', totalsX, afterTable + rowH * 0.8)
  doc.text(`GST (${(0.1 * 100).toFixed(0)}%)`, totalsX, afterTable + rowH * 1.8)

  doc.setTextColor(...DARK)
  doc.text(fmt(subtotal), pageW - 14, afterTable + rowH * 0.8, { align: 'right' })
  doc.text(fmt(gst), pageW - 14, afterTable + rowH * 1.8, { align: 'right' })

  // Total row
  const totalRowY = afterTable + rowH * 2.2
  doc.setFillColor(...BRAND_BLUE)
  doc.roundedRect(totalsX - 6, totalRowY, totalsW + 6, rowH + 2, 2, 2, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10.5)
  doc.setTextColor(255, 255, 255)
  doc.text('TOTAL (incl. GST)', totalsX, totalRowY + rowH * 0.72)
  doc.text(fmt(total), pageW - 14, totalRowY + rowH * 0.72, { align: 'right' })

  // Notes
  if (quote.notes) {
    const notesY = totalRowY + rowH + 14
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...DARK)
    doc.text('Notes', 14, notesY)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MID_GRAY)
    const lines = doc.splitTextToSize(quote.notes, pageW - 28)
    doc.text(lines, 14, notesY + 5)
  }

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(...MID_GRAY)
  doc.text('Generated by CatchQuote · catchquote.io', pageW / 2, pageH - 8, { align: 'center' })

  const filename = `quote-${(quote.quoteNumber || 'draft').replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`
  doc.save(filename)
}
